version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ml
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
  ml:
    build: ./ml
    volumes:
      - ./ml:/app
    ports:
      - "9000:9000"
    env_file:
      - .env
